# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: IndexEducation.ClientPRONOTE2024-64bit
PackageVersion: 3.11.0
DefaultLocale: fr-FR
ManifestType: version
ManifestVersion: 1.9.0
