# Created using wingetcreate 1.9.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: IndexEducation.Pronote
PackageVersion: 3.11.0
DefaultLocale: fr-Fr
ManifestType: version
ManifestVersion: 1.9.0
